export default function Home() {
  return (
    <main style={{minHeight: '100vh', background: '#030712', color: 'white', fontFamily: 'sans-serif'}}>
      
      {/* Header */}
      <header style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '24px 48px', borderBottom: '1px solid #1f2937'}}>
        <div style={{fontSize: '20px', fontWeight: 'bold', color: '#22d3ee'}}>✦ CopyAI Pro</div>
        <button style={{background: '#06b6d4', color: 'black', fontWeight: 'bold', padding: '10px 24px', borderRadius: '999px', border: 'none', cursor: 'pointer', fontSize: '14px'}}>
          Get Started Free
        </button>
      </header>

      {/* Hero */}
      <section style={{textAlign: 'center', padding: '100px 48px'}}>
        <div style={{display: 'inline-block', background: '#083344', color: '#22d3ee', fontSize: '12px', fontWeight: 'bold', padding: '6px 16px', borderRadius: '999px', marginBottom: '24px', border: '1px solid #164e63'}}>
          AI-Powered Content — Delivered in Seconds
        </div>
        <h1 style={{fontSize: '52px', fontWeight: 'bold', marginBottom: '24px', lineHeight: '1.2'}}>
          Professional Content<br />
          <span style={{color: '#22d3ee'}}>Written by AI.</span> Ready Instantly.
        </h1>
        <p style={{color: '#9ca3af', fontSize: '20px', marginBottom: '40px', maxWidth: '600px', margin: '0 auto 40px'}}>
          Blog posts, SEO articles, and ad copy generated by Claude AI and delivered to your inbox. No waiting. No freelancers.
        </p>
        <button style={{background: '#06b6d4', color: 'black', fontWeight: 'bold', padding: '16px 40px', borderRadius: '999px', border: 'none', cursor: 'pointer', fontSize: '18px', marginRight: '16px'}}>
          Start Free Trial
        </button>
        <button style={{background: 'transparent', color: 'white', padding: '16px 40px', borderRadius: '999px', border: '1px solid #4b5563', cursor: 'pointer', fontSize: '18px'}}>
          See Examples
        </button>
      </section>

      {/* How It Works */}
      <section style={{padding: '80px 48px', background: '#111827'}}>
        <h2 style={{fontSize: '32px', fontWeight: 'bold', textAlign: 'center', marginBottom: '64px'}}>How It Works</h2>
        <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '32px', maxWidth: '900px', margin: '0 auto'}}>
          <div style={{textAlign: 'center'}}>
            <div style={{fontSize: '48px', marginBottom: '16px'}}>📝</div>
            <h3 style={{fontWeight: 'bold', fontSize: '18px', marginBottom: '8px'}}>1. Tell Us What You Need</h3>
            <p style={{color: '#9ca3af', fontSize: '14px'}}>Enter your topic, tone, and target audience in seconds.</p>
          </div>
          <div style={{textAlign: 'center'}}>
            <div style={{fontSize: '48px', marginBottom: '16px'}}>🤖</div>
            <h3 style={{fontWeight: 'bold', fontSize: '18px', marginBottom: '8px'}}>2. AI Gets to Work</h3>
            <p style={{color: '#9ca3af', fontSize: '14px'}}>Claude AI writes your content instantly.</p>
          </div>
          <div style={{textAlign: 'center'}}>
            <div style={{fontSize: '48px', marginBottom: '16px'}}>📧</div>
            <h3 style={{fontWeight: 'bold', fontSize: '18px', marginBottom: '8px'}}>3. Receive and Publish</h3>
            <p style={{color: '#9ca3af', fontSize: '14px'}}>Get polished content by email, ready to copy and paste.</p>
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section style={{padding: '80px 48px'}}>
        <h2 style={{fontSize: '32px', fontWeight: 'bold', textAlign: 'center', marginBottom: '16px'}}>Simple Pricing</h2>
        <p style={{color: '#9ca3af', textAlign: 'center', marginBottom: '64px'}}>Start free. Scale as you grow.</p>
        <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '32px', maxWidth: '1000px', margin: '0 auto'}}>
          
          <div style={{background: '#111827', border: '1px solid #1f2937', borderRadius: '16px', padding: '32px'}}>
            <h3 style={{fontWeight: 'bold', fontSize: '18px', marginBottom: '8px'}}>Starter</h3>
            <div style={{fontSize: '40px', fontWeight: 'bold', marginBottom: '4px'}}>$9<span style={{fontSize: '18px', color: '#9ca3af'}}>/mo</span></div>
            <p style={{color: '#9ca3af', fontSize: '14px', marginBottom: '32px'}}>Perfect to get started</p>
            <ul style={{listStyle: 'none', padding: 0, marginBottom: '32px'}}>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ 5 blog posts/month</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ 500 words each</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ Email delivery</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ SEO optimized</li>
            </ul>
            <button style={{width: '100%', background: 'transparent', color: 'white', padding: '12px', borderRadius: '999px', border: '1px solid #4b5563', cursor: 'pointer', fontWeight: 'bold'}}>
              Get Started
            </button>
          </div>

          <div style={{background: '#083344', border: '2px solid #06b6d4', borderRadius: '16px', padding: '32px', position: 'relative'}}>
            <div style={{position: 'absolute', top: '-12px', left: '50%', transform: 'translateX(-50%)', background: '#06b6d4', color: 'black', fontSize: '11px', fontWeight: 'bold', padding: '4px 16px', borderRadius: '999px'}}>
              MOST POPULAR
            </div>
            <h3 style={{fontWeight: 'bold', fontSize: '18px', marginBottom: '8px'}}>Pro</h3>
            <div style={{fontSize: '40px', fontWeight: 'bold', marginBottom: '4px'}}>$29<span style={{fontSize: '18px', color: '#9ca3af'}}>/mo</span></div>
            <p style={{color: '#9ca3af', fontSize: '14px', marginBottom: '32px'}}>For serious content creators</p>
            <ul style={{listStyle: 'none', padding: 0, marginBottom: '32px'}}>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ 20 blog posts/month</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ 1,000 words each</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ Email delivery</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ SEO + meta descriptions</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ Ad copy included</li>
            </ul>
            <button style={{width: '100%', background: '#06b6d4', color: 'black', padding: '12px', borderRadius: '999px', border: 'none', cursor: 'pointer', fontWeight: 'bold'}}>
              Get Started
            </button>
          </div>

          <div style={{background: '#111827', border: '1px solid #1f2937', borderRadius: '16px', padding: '32px'}}>
            <h3 style={{fontWeight: 'bold', fontSize: '18px', marginBottom: '8px'}}>Business</h3>
            <div style={{fontSize: '40px', fontWeight: 'bold', marginBottom: '4px'}}>$69<span style={{fontSize: '18px', color: '#9ca3af'}}>/mo</span></div>
            <p style={{color: '#9ca3af', fontSize: '14px', marginBottom: '32px'}}>For agencies and teams</p>
            <ul style={{listStyle: 'none', padding: 0, marginBottom: '32px'}}>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ Unlimited posts</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ Up to 2,000 words</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ Priority delivery</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ Full SEO package</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ Social media captions</li>
              <li style={{marginBottom: '12px', fontSize: '14px', color: '#d1d5db'}}>✓ Email sequences</li>
            </ul>
            <button style={{width: '100%', background: 'transparent', color: 'white', padding: '12px', borderRadius: '999px', border: '1px solid #4b5563', cursor: 'pointer', fontWeight: 'bold'}}>
              Get Started
            </button>
          </div>

        </div>
      </section>

      {/* Footer */}
      <footer style={{textAlign: 'center', padding: '40px', borderTop: '1px solid #1f2937', color: '#6b7280', fontSize: '14px'}}>
        2026 CopyAI Pro. Built with Claude AI.
      </footer>

    </main>
  );
}